version: '3'

services:
  neo4j:
    build:
      context: .
      args:
        GRAPHIUM_BRANCH_NAME: develop
    container_name: neo4j-graphium
    environment:
      - "NEO4J_AUTH=none"
      - "GRAPHIUM_SERVER_NAME=satellite_graphserver_neo4j"
      - "GRAPHIUM_SERVER_URI=http://localhost:7474/graphium/api"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./logs:/logs